name: TestCD

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: rsync deployments
       uses: appleboy/ssh-action@master
       with:
        script: "cd /home/dldservicio/rental-car && git pull"
        host: "38.7.129.13"
        username: "dldservicio"
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: "dldservicio"
